myData <- read.table("household_power_consumption.txt", sep=";", na.strings = "?",header=TRUE, stringsAsFactors =FALSE)
plotData <- subset(myData, myData$Date == "1/2/2007" | myData$Date == "2/2/2007")
plotData$DateTime <- strptime(paste(plotData$Date, plotData$Time), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width = 480, height = 480)
plot(plotData$DateTime,plotData$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(plotData$DateTime,plotData$Sub_metering_2,type="l",col="red")
lines(plotData$DateTime,plotData$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=1,col=c("black","red","blue"))
dev.off()