myData <- read.table("household_power_consumption.txt", sep=";", na.strings = "?",header=TRUE, stringsAsFactors =FALSE)
plotData <- subset(myData, myData$Date == "1/2/2007" | myData$Date == "2/2/2007")
plotData$DateTime <- strptime(paste(plotData$Date, plotData$Time), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(plotData$DateTime,plotData$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(plotData$DateTime,plotData$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(plotData$DateTime,plotData$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(plotData$DateTime,plotData$Sub_metering_2,type="l",col="red")
lines(plotData$DateTime,plotData$Sub_metering_3,type="l",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,lwd=1,col=c("black","red","blue"),bty="n")
plot(plotData$DateTime,plotData$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()